Added man page generation and improved copying.

diff --git a/spk/aspk/daemon/install b/spk/aspk/daemon/install
--- a/spk/aspk/daemon/install
+++ b/spk/aspk/daemon/install
@@ -1,9 +1,29 @@
 #!/bin/sh
 
+
+if [ $UID -ne 0 ];
+then
+    echo "You must be root to run this program"
+    exit 1
+fi
+echo "You can only run this from aspkserver."
+echo "If the aspkserver login fails, that's the reason."
+
+source ../../../../../doc/webdir.sh
+
 SERVICE_ROOT=spkcmp
+SERVICE_HOST=aspkserver
 
-cp ${SERVICE_ROOT}d /etc/rc.d/init.d
-cp ${SERVICE_ROOT}testd /etc/rc.d/init.d
-cp ${SERVICE_ROOT}d.pl /usr/local/bin/spktest
+scp ${SERVICE_ROOT}d ${SERVICE_HOST}:/etc/rc.d/init.d
+scp ${SERVICE_ROOT}testd ${SERVICE_HOST}:/etc/rc.d/init.d
+scp ${SERVICE_ROOT}d.pl ${SERVICE_HOST}:/usr/local/bin/spktest
 
+echo "installed ${SERVICE_HOST}:/etc/rc.d/init.d/${SERVICE_ROOT}d
+echo "installed ${SERVICE_HOST}:/etc/rc.d/init.d/${SERVICE_ROOT}testd
+echo "installed ${SERVICE_HOST}:/usr/local/bin/spktest/${SERVICE_ROOT}d.pl
+
+D=${SERVICE_ROOT}d
+pod2html $D.pl > $D.pl.html
+
+scp $D.pl.html $WEBHOST:/$WEBDIR/man/$D.pl.html
 
