roll back

diff --git a/spk/aspk/daemon/installer b/spk/aspk/daemon/installer
--- a/spk/aspk/daemon/installer
+++ b/spk/aspk/daemon/installer
@@ -1,24 +1,29 @@
 #!/bin/sh
 
-echo "This installer has been modified from the CVS/original version."
-echo "This installs stuff on localhost only."
+
+if [ $UID -ne 0 ];
+then
+    echo "You must be root on aspkserver to perform this installation."
+    echo "Be sure to use su - (not just su) when becoming root."
+    exit 1
+fi
+echo "You can only run this from aspkserver."
+echo "If the aspkserver login fails, that's the reason."
 
 source ../../../../../doc/webdir.sh
 
 SERVICE_ROOT=spkcmp
-SERVICE_HOST=localhost
+SERVICE_HOST=aspkserver
 
 cp ${SERVICE_ROOT}d /etc/rc.d/init.d
 cp ${SERVICE_ROOT}testd /etc/rc.d/init.d
 cp ${SERVICE_ROOT}d.pl /usr/local/bin/spktest
-cp ${SERVICE_ROOT}monitord /etc/rc.d/init.d
 
 echo "installed ${SERVICE_HOST}:/etc/rc.d/init.d/${SERVICE_ROOT}d"
 echo "installed ${SERVICE_HOST}:/etc/rc.d/init.d/${SERVICE_ROOT}testd"
 echo "installed ${SERVICE_HOST}:/usr/local/bin/spktest/${SERVICE_ROOT}d.pl"
-echo "installed ${SERVICE_HOST}:/etc/rc.d/init.d/${SERVICE_ROOT}monitord"
 
 D=${SERVICE_ROOT}d
 
-#scp $D.pl.html $WEBHOST:/$WEBDIR/man/$D.pl.html
+scp $D.pl.html $WEBHOST:/$WEBDIR/man/$D.pl.html
 
